# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: 5.3
    - php: 5.6
    - php: 7.0
    - php: hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction

script:
 - mkdir -p build/logs
 - phpunit --configuration TestSuite/phpunit.xml --coverage-text --debug
 - phpunit --configuration TestSuite/phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v
 - CODECLIMATE_REPO_TOKEN="1a500cc99253603dbf5453e471a3de9b2b31300594d982f1ca798c6feeb79998" ./vendor/bin/test-reporter --stdout > codeclimate.json
 - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
 # Bugfix TravisCI:
 - set +e

notifications:
  email: false

branches:
  only:
    - master
    - development
